# utils/disposal_info.py

DISPOSAL_DATA = {
    "cardboard": {
        "emoji": "📦",
        "color": "#92400e",
        "bg":    "#fef3c7",
        "accent":"#f59e0b",
        "bin":   "Blue Recycling Bin",
        "action":"Recycle",
        "tip":   "Flatten and keep dry.",
        "steps": [
            "Remove all tape, staples and plastic wrapping",
            "Flatten the box completely to save bin space",
            "Keep dry — wet cardboard cannot be recycled",
            "Place in blue recycling bin or recycling centre",
            "Greasy pizza boxes go in general waste",
        ],
        "fact":      "Recycling one tonne of cardboard saves 17 trees.",
        "recyclable": True,
        "co2":       "1.1 kg CO₂ saved/kg",
        "decompose": "2 months",
        "rate":      "89%",
    },
    "glass": {
        "emoji": "🫙",
        "color": "#1e3a5f",
        "bg":    "#dbeafe",
        "accent":"#3b82f6",
        "bin":   "Green / Brown Bottle Bank",
        "action":"Recycle",
        "tip":   "Rinse and sort by colour.",
        "steps": [
            "Rinse bottles and jars to remove food residue",
            "Remove metal lids — recycle them separately",
            "Do NOT include window glass, mirrors or Pyrex",
            "Separate by colour at bottle banks if required",
            "Broken glass: wrap in newspaper, put in general waste",
        ],
        "fact":      "Glass can be recycled indefinitely without loss of quality.",
        "recyclable": True,
        "co2":       "0.3 kg CO₂ saved/kg",
        "decompose": "1 million years",
        "rate":      "67%",
    },
    "metal": {
        "emoji": "🥫",
        "color": "#1f2937",
        "bg":    "#f3f4f6",
        "accent":"#6b7280",
        "bin":   "Blue Recycling Bin",
        "action":"Recycle",
        "tip":   "Rinse cans and crush to save space.",
        "steps": [
            "Rinse food and drink cans thoroughly",
            "Crush cans to save space in the bin",
            "Aluminium foil: scrunch into a ball first",
            "Aerosol cans: ensure completely empty before recycling",
            "Remove paper labels where possible",
        ],
        "fact":      "Recycling aluminium uses only 5% of the energy of new production.",
        "recyclable": True,
        "co2":       "9.1 kg CO₂ saved/kg",
        "decompose": "200–500 years",
        "rate":      "70%",
    },
    "paper": {
        "emoji": "📄",
        "color": "#14532d",
        "bg":    "#dcfce7",
        "accent":"#22c55e",
        "bin":   "Blue Recycling Bin",
        "action":"Recycle",
        "tip":   "Keep dry — wet paper cannot be recycled.",
        "steps": [
            "Keep paper clean and dry before recycling",
            "OK: newspapers, magazines, office paper, envelopes",
            "NOT OK: tissue paper, paper towels, waxed paper",
            "Shredded paper: place in a sealed paper bag",
            "Remove plastic windows from envelopes first",
        ],
        "fact":      "Each tonne of recycled paper saves 24 trees and 7,000 litres of water.",
        "recyclable": True,
        "co2":       "0.9 kg CO₂ saved/kg",
        "decompose": "2–6 weeks",
        "rate":      "66%",
    },
    "plastic": {
        "emoji": "🧴",
        "color": "#7c2d12",
        "bg":    "#fff7ed",
        "accent":"#f97316",
        "bin":   "Check Symbol — #1 & #2 Recyclable",
        "action":"Check Symbol",
        "tip":   "Look for the triangle number on the bottom.",
        "steps": [
            "Look for triangle recycling symbol on the bottom",
            "#1 (PET) and #2 (HDPE) are widely accepted",
            "#3–#7: check your local council guidelines",
            "Rinse containers to remove food residue",
            "Plastic bags: take to supermarket drop-off points",
        ],
        "fact":      "Only 9% of all plastic ever produced has been recycled globally.",
        "recyclable": True,
        "co2":       "1.5 kg CO₂ saved/kg",
        "decompose": "450+ years",
        "rate":      "9%",
    },
    "trash": {
        "emoji": "🗑️",
        "color": "#374151",
        "bg":    "#f9fafb",
        "accent":"#9ca3af",
        "bin":   "Black General Waste Bin",
        "action":"General Waste",
        "tip":   "Minimise by reducing consumption.",
        "steps": [
            "Place in black general waste bin",
            "Check if any components can be separated and recycled",
            "Hazardous items: take to special collection points",
            "Consider if the item can be repaired or reused",
            "Try to reduce packaging in future purchases",
        ],
        "fact":      "The average person generates over 4 lbs of trash per day.",
        "recyclable": False,
        "co2":       "Reduce consumption",
        "decompose": "Varies widely",
        "rate":      "0%",
    },
    "biological": {
        "emoji": "🥬",
        "color": "#166534",
        "bg":    "#f0fdf4",
        "accent":"#16a34a",
        "bin":   "Brown Compost / Food Waste Bin",
        "action":"Compost",
        "tip":   "Food waste goes in the compost bin.",
        "steps": [
            "Place in brown compost or food waste bin",
            "Accepted: fruit, vegetables, meat, fish, dairy",
            "Also accepted: tea bags, coffee grounds, eggshells",
            "Do NOT include liquids, oils or heavily packaged food",
            "Home composting is an excellent alternative",
        ],
        "fact":      "Food waste in landfill produces methane — 25x more potent than CO₂.",
        "recyclable": True,
        "co2":       "Composting saves 0.5 kg CO₂/kg",
        "decompose": "2–6 weeks (compost)",
        "rate":      "Compostable",
    },
    "battery": {
        "emoji": "🔋",
        "color": "#1e3a8a",
        "bg":    "#eff6ff",
        "accent":"#3b82f6",
        "bin":   "Battery Recycling Point",
        "action":"Special Recycling",
        "tip":   "Never put batteries in general waste — they are hazardous.",
        "steps": [
            "NEVER put batteries in general waste or recycling bins",
            "Take to a battery recycling point — most supermarkets have one",
            "Tape the terminals of lithium batteries before disposal",
            "Rechargeable batteries: take to electronics recycling point",
            "Car batteries: return to a garage or auto parts store",
        ],
        "fact":      "Batteries contain toxic materials that can leach into soil and water.",
        "recyclable": True,
        "co2":       "Special processing required",
        "decompose": "100 years",
        "rate":      "45% (specialist recycling)",
    },
    "shoes": {
        "emoji": "👟",
        "color": "#713f12",
        "bg":    "#fefce8",
        "accent":"#ca8a04",
        "bin":   "Charity Shop / Textile Bank",
        "action":"Donate or Textile Bank",
        "tip":   "If wearable, donate. If not, use a textile bank.",
        "steps": [
            "If still wearable: donate to charity shops or clothing banks",
            "If worn out: place in a textile recycling bank",
            "Many shoe brands have take-back recycling programmes",
            "Check if local council collects textiles kerbside",
            "Do NOT put shoes in general recycling bins",
        ],
        "fact":      "300 million pairs of shoes are thrown away in the UK every year.",
        "recyclable": True,
        "co2":       "Donation saves ~4 kg CO₂/pair",
        "decompose": "30–40 years",
        "rate":      "Donate or textile recycle",
    },
    "clothes": {
        "emoji": "👕",
        "color": "#581c87",
        "bg":    "#faf5ff",
        "accent":"#9333ea",
        "bin":   "Charity Shop / Textile Bank",
        "action":"Donate or Textile Bank",
        "tip":   "Clothes are never general waste — always donate or recycle.",
        "steps": [
            "If good condition: donate to charity shops or online",
            "If worn out: place in a textile recycling bank",
            "Many fashion brands (H&M, Zara, M&S) have in-store take-back",
            "Check if local council collects textiles kerbside",
            "Repair where possible — even small repairs extend garment life",
        ],
        "fact":      "The fashion industry produces 10% of global carbon emissions.",
        "recyclable": True,
        "co2":       "Donation saves ~2 kg CO₂/garment",
        "decompose": "20–200 years depending on fabric",
        "rate":      "Textile recycling available",
    },
}

GLOBAL_STATS = [
    {"label": "Waste generated annually",  "value": "2.01B tonnes",  "icon": "🌍"},
    {"label": "Global recycling rate",      "value": "Only 19%",      "icon": "♻️"},
    {"label": "Plastic enters oceans/year", "value": "8M tonnes",     "icon": "🌊"},
    {"label": "Landfill methane share",     "value": "11% of global", "icon": "☁️"},
]