# utils/disposal_info.py

DISPOSAL_DATA = {
    "cardboard": {
        "emoji": "📦",
        "color": "#92400e",
        "bg":    "#fef3c7",
        "accent":"#f59e0b",
        "bin":   "Blue Recycling Bin",
        "action":"Recycle",
        "tip":   "Flatten and keep dry.",
        "steps": [
            "Remove all tape, staples and plastic wrapping",
            "Flatten the box completely to save bin space",
            "Keep dry — wet cardboard cannot be recycled",
            "Place in blue recycling bin or recycling centre",
            "Greasy pizza boxes go in general waste",
        ],
        "fact":      "Recycling one tonne of cardboard saves 17 trees.",
        "recyclable": True,
        "co2":       "1.1 kg CO₂ saved/kg",
        "decompose": "2 months",
        "rate":      "89%",
    },
    "glass": {
        "emoji": "🫙",
        "color": "#1e3a5f",
        "bg":    "#dbeafe",
        "accent":"#3b82f6",
        "bin":   "Green / Brown Bottle Bank",
        "action":"Recycle",
        "tip":   "Rinse and sort by colour.",
        "steps": [
            "Rinse bottles and jars to remove food residue",
            "Remove metal lids — recycle them separately",
            "Do NOT include window glass, mirrors or Pyrex",
            "Separate by colour at bottle banks if required",
            "Broken glass: wrap in newspaper, put in general waste",
        ],
        "fact":      "Glass can be recycled indefinitely without loss of quality.",
        "recyclable": True,
        "co2":       "0.3 kg CO₂ saved/kg",
        "decompose": "1 million years",
        "rate":      "67%",
    },
    "metal": {
        "emoji": "🥫",
        "color": "#1f2937",
        "bg":    "#f3f4f6",
        "accent":"#6b7280",
        "bin":   "Blue Recycling Bin",
        "action":"Recycle",
        "tip":   "Rinse cans and crush to save space.",
        "steps": [
            "Rinse food and drink cans thoroughly",
            "Crush cans to save space in the bin",
            "Aluminium foil: scrunch into a ball first",
            "Aerosol cans: ensure completely empty before recycling",
            "Remove paper labels where possible",
        ],
        "fact":      "Recycling aluminium uses only 5% of the energy of new production.",
        "recyclable": True,
        "co2":       "9.1 kg CO₂ saved/kg",
        "decompose": "200–500 years",
        "rate":      "70%",
    },
    "paper": {
        "emoji": "📄",
        "color": "#14532d",
        "bg":    "#dcfce7",
        "accent":"#22c55e",
        "bin":   "Blue Recycling Bin",
        "action":"Recycle",
        "tip":   "Keep dry — wet paper cannot be recycled.",
        "steps": [
            "Keep paper clean and dry before recycling",
            "OK: newspapers, magazines, office paper, envelopes",
            "NOT OK: tissue paper, paper towels, waxed paper",
            "Shredded paper: place in a sealed paper bag",
            "Remove plastic windows from envelopes first",
        ],
        "fact":      "Each tonne of recycled paper saves 24 trees and 7,000 litres of water.",
        "recyclable": True,
        "co2":       "0.9 kg CO₂ saved/kg",
        "decompose": "2–6 weeks",
        "rate":      "66%",
    },
    "plastic": {
        "emoji": "🧴",
        "color": "#7c2d12",
        "bg":    "#fff7ed",
        "accent":"#f97316",
        "bin":   "Check Symbol — #1 & #2 Recyclable",
        "action":"Check Symbol",
        "tip":   "Look for the triangle number on the bottom.",
        "steps": [
            "Look for triangle recycling symbol on the bottom",
            "#1 (PET) and #2 (HDPE) are widely accepted",
            "#3–#7: check your local council guidelines",
            "Rinse containers to remove food residue",
            "Plastic bags: take to supermarket drop-off points",
        ],
        "fact":      "Only 9% of all plastic ever produced has been recycled globally.",
        "recyclable": True,
        "co2":       "1.5 kg CO₂ saved/kg",
        "decompose": "450+ years",
        "rate":      "9%",
    },
    "trash": {
        "emoji": "🗑️",
        "color": "#374151",
        "bg":    "#f9fafb",
        "accent":"#9ca3af",
        "bin":   "Black General Waste Bin",
        "action":"General Waste",
        "tip":   "Minimise by reducing consumption.",
        "steps": [
            "Place in black general waste bin",
            "Check if any components can be separated and recycled",
            "Hazardous items: take to special collection points",
            "Consider if the item can be repaired or reused",
            "Try to reduce packaging in future purchases",
        ],
        "fact":      "The average person generates over 4 lbs of trash per day.",
        "recyclable": False,
        "co2":       "Reduce consumption",
        "decompose": "Varies widely",
        "rate":      "0%",
    },
    "biological": {
        "emoji": "🥬",
        "color": "#166534",
        "bg":    "#f0fdf4",
        "accent":"#16a34a",
        "bin":   "Brown Compost / Food Waste Bin",
        "action":"Compost",
        "tip":   "Food waste goes in the compost bin.",
        "steps": [
            "Place in brown compost or food waste bin",
            "Accepted: fruit, vegetables, meat, fish, dairy",
            "Also accepted: tea bags, coffee grounds, eggshells",
            "Do NOT include liquids, oils or heavily packaged food",
            "Home composting is an excellent alternative",
        ],
        "fact":      "Food waste in landfill produces methane — 25x more potent than CO₂.",
        "recyclable": True,
        "co2":       "Composting saves 0.5 kg CO₂/kg",
        "decompose": "2–6 weeks (compost)",
        "rate":      "Compostable",
    },
    "battery": {
        "emoji": "🔋",
        "color": "#1e3a8a",
        "bg":    "#eff6ff",
        "accent":"#3b82f6",
        "bin":   "Battery Recycling Point",
        "action":"Special Recycling",
        "tip":   "Never put batteries in general waste — they are hazardous.",
        "steps": [
            "NEVER put batteries in general waste or recycling bins",
            "Take to a battery recycling point — most supermarkets have one",
            "Tape the terminals of lithium batteries before disposal",
            "Rechargeable batteries: take to electronics recycling point",
            "Car batteries: return to a garage or auto parts store",
        ],
        "fact":      "Batteries contain toxic materials that can leach into soil and water.",
        "recyclable": True,
        "co2":       "Special processing required",
        "decompose": "100 years",
        "rate":      "45% (specialist recycling)",
    },
    "shoes": {
        "emoji": "👟",
        "color": "#713f12",
        "bg":    "#fefce8",
        "accent":"#ca8a04",
        "bin":   "Charity Shop / Textile Bank",
        "action":"Donate or Textile Bank",
        "tip":   "If wearable, donate. If not, use a textile bank.",
        "steps": [
            "If still wearable: donate to charity shops or clothing banks",
            "If worn out: place in a textile recycling bank",
            "Many shoe brands have take-back recycling programmes",
            "Check if local council collects textiles kerbside",
            "Do NOT put shoes in general recycling bins",
        ],
        "fact":      "300 million pairs of shoes are thrown away in the UK every year.",
        "recyclable": True,
        "co2":       "Donation saves ~4 kg CO₂/pair",
        "decompose": "30–40 years",
        "rate":      "Donate or textile recycle",
    },
    "clothes": {
        "emoji": "👕",
        "color": "#581c87",
        "bg":    "#faf5ff",
        "accent":"#9333ea",
        "bin":   "Charity Shop / Textile Bank",
        "action":"Donate or Textile Bank",
        "tip":   "Clothes are never general waste — always donate or recycle.",
        "steps": [
            "If good condition: donate to charity shops or online",
            "If worn out: place in a textile recycling bank",
            "Many fashion brands (H&M, Zara, M&S) have in-store take-back",
            "Check if local council collects textiles kerbside",
            "Repair where possible — even small repairs extend garment life",
        ],
        "fact":      "The fashion industry produces 10% of global carbon emissions.",
        "recyclable": True,
        "co2":       "Donation saves ~2 kg CO₂/garment",
        "decompose": "20–200 years depending on fabric",
        "rate":      "Textile recycling available",
    },
}

GLOBAL_STATS = [
    {"label": "Waste generated annually",  "value": "2.01B tonnes",  "icon": "🌍"},
    {"label": "Global recycling rate",      "value": "Only 19%",      "icon": "♻️"},
    {"label": "Plastic enters oceans/year", "value": "8M tonnes",     "icon": "🌊"},
    {"label": "Landfill methane share",     "value": "11% of global", "icon": "☁️"},
]

RECYCLE_GUIDE = {
    "cardboard": {
        "title": "How to Recycle Cardboard",
        "steps": [
            "Remove all tape, staples, plastic wrapping and foam inserts completely",
            "Break down all boxes flat — this is mandatory at most recycling facilities",
            "Check for grease or food contamination — a light stain is OK, heavy soiling is not",
            "Keep cardboard dry — even brief rain exposure can make it unrecyclable",
            "Bundle flattened boxes together and tie with string if needed for kerbside collection",
            "Very large boxes: cut them down to fit your recycling bin or take to recycling centre",
            "Waxed cardboard (e.g. some fruit boxes): cannot be recycled — goes in general waste",
        ],
        "tip": "A quick test: if you can tear it easily and it feels like normal card, it is recyclable.",
        "recycled_into": "New cardboard boxes, paper bags, newspapers, egg cartons",
        "process": "Shredded → Pulped with water → Filtered → Pressed into sheets → Dried → New cardboard",
    },
    "glass": {
        "title": "How to Recycle Glass",
        "steps": [
            "Rinse bottles and jars to remove all food and drink residue",
            "Remove metal lids and caps — recycle these separately in the metal bin",
            "Remove paper labels if possible, though most facilities handle these automatically",
            "Do NOT include: window glass, mirrors, Pyrex, drinking glasses, light bulbs — these have different compositions",
            "At a bottle bank: separate by colour — clear, green, brown — if required in your area",
            "Broken glass: wrap carefully in several layers of newspaper, tape it, label it 'broken glass', place in general waste",
            "Never put broken glass loose in recycling bins — it is a safety hazard for workers",
        ],
        "tip": "Glass can be recycled endlessly with no loss of quality — every bottle recycled saves energy.",
        "recycled_into": "New glass bottles and jars, fibreglass insulation, road aggregate",
        "process": "Sorted by colour → Crushed into cullet → Melted in furnace → Moulded into new glass",
    },
    "metal": {
        "title": "How to Recycle Metal",
        "steps": [
            "Rinse all food and drink cans thoroughly — residue can contaminate other recyclables",
            "Crush aluminium cans if possible to save space, but this is optional",
            "Aluminium foil: scrunch multiple pieces together into a ball at least 5cm wide before recycling",
            "Aerosol cans: ensure completely empty — press nozzle until no gas comes out — then recycle",
            "Steel tins (baked beans, soup): rinse and recycle with the lid tucked inside",
            "Do NOT recycle: paint cans with dried paint, pressurised gas cylinders, loose sharp metal pieces",
            "Large scrap metal (pipes, wire, appliances): take to a scrap metal dealer or recycling centre",
        ],
        "tip": "Recycling one aluminium can saves enough energy to power a TV for 3 hours.",
        "recycled_into": "New cans, car parts, aircraft parts, building materials, bicycles",
        "process": "Shredded → Sorted magnetically (steel) or by eddy current (aluminium) → Melted → Rolled into sheets",
    },
    "paper": {
        "title": "How to Recycle Paper",
        "steps": [
            "Keep paper clean and completely dry — wet paper fibres are damaged and cannot be recycled",
            "Acceptable: newspapers, magazines, office paper, envelopes, junk mail, catalogues, receipts",
            "Remove plastic wrap from magazines before recycling — the paper inside is fine",
            "Shredded paper: place inside a sealed paper bag or envelope to prevent it scattering",
            "NOT acceptable: tissues, paper towels, kitchen roll, waxed paper, greasy paper — these go in general waste",
            "Remove plastic windows from envelopes if possible, though many facilities can handle them",
            "Staples and paper clips are fine — they are removed during processing",
        ],
        "tip": "Paper can be recycled 5–7 times before the fibres become too short to bond.",
        "recycled_into": "Newspapers, cardboard, toilet paper, egg cartons, insulation material",
        "process": "Soaked in water to create pulp → Cleaned and de-inked → Screened → Pressed into sheets → Dried",
    },
    "plastic": {
        "title": "How to Recycle Plastic",
        "steps": [
            "Find the triangle recycling symbol on the bottom of the item — it contains a number 1–7",
            "#1 PET (water bottles, food trays) — widely recyclable everywhere",
            "#2 HDPE (milk bottles, shampoo bottles) — widely recyclable everywhere",
            "#3–#7: check your local council website — acceptance varies significantly by area",
            "Rinse all containers to remove food residue — even a small amount can contaminate a batch",
            "Plastic bags and film: do NOT put in kerbside bins — take to supermarket collection points",
            "Squash bottles flat and replace the cap before recycling to save space",
        ],
        "tip": "When in doubt, check your local council recycling guide — rules vary between areas.",
        "recycled_into": "New bottles, fleece clothing, carpets, garden furniture, drainage pipes",
        "process": "Sorted by resin type → Shredded into flakes → Washed → Melted into pellets → Moulded into new products",
    },
    "trash": {
        "title": "Reducing General Waste",
        "steps": [
            "Before throwing away, ask: can this be repaired, reused, donated, or composted?",
            "Separate out any recyclable components before placing in general waste",
            "Food scraps: check if your council offers food waste collection or start home composting",
            "Hazardous items (batteries, paint, chemicals): never put in general waste — take to hazardous waste collection",
            "Electronics: never put in general waste — take to an e-waste collection point or retailer take-back",
            "Clothing and textiles: even worn-out items can go to textile banks, never general waste",
            "Reduce future waste by choosing products with less packaging and buying in bulk",
        ],
        "tip": "General waste goes to landfill or incineration — reducing it starts at the point of purchase.",
        "recycled_into": "General waste cannot be recycled — focus on reduction and separation",
        "process": "Collected → Sorted at waste facility → Residual waste to landfill or energy-from-waste plant",
    },
    "biological": {
        "title": "How to Compost Biological Waste",
        "steps": [
            "Place in your brown food waste bin if your council collects it kerbside",
            "Accepted: fruit and vegetable peelings, cooked food, meat, fish, dairy, bread, coffee grounds, tea bags",
            "Do NOT include: liquids, oils, heavily packaged food, non-food items",
            "For home composting: fruit, vegetables, tea bags, coffee grounds, eggshells are ideal",
            "Avoid adding meat, fish or dairy to home compost as it attracts pests — use a council bin instead",
            "Layer green waste (food) with brown waste (cardboard, leaves) in a home compost bin",
            "Turn the compost every few weeks to speed up decomposition and prevent odours",
        ],
        "tip": "Home compost takes 3–6 months to become rich fertiliser — great for gardens.",
        "recycled_into": "Compost for soil improvement, biogas (anaerobic digestion), liquid fertiliser",
        "process": "Collected → Anaerobic digestion plant → Biogas captured for energy → Digestate used as fertiliser",
    },
    "battery": {
        "title": "How to Recycle Batteries",
        "steps": [
            "NEVER put batteries in general waste or recycling bins — they are hazardous and can cause fires",
            "Collect used batteries in a small container at home until you have enough to take for recycling",
            "Drop off at a battery recycling point — found at most supermarkets, DIY stores and councils",
            "Lithium batteries (laptops, phones): tape the terminals with electrical tape before disposal to prevent short circuits",
            "Rechargeable batteries: most electronics retailers (Currys, Argos) accept them for recycling",
            "Car and van batteries: return to a garage, auto parts store or recycling centre — they have significant scrap value",
            "Damaged or swollen batteries: place in a fireproof container and take directly to a recycling centre",
        ],
        "tip": "45% of batteries are recycled in the UK — the rest end up in landfill leaching toxic chemicals.",
        "recycled_into": "Recovered metals (lithium, cobalt, nickel, lead) used in new batteries and electronics",
        "process": "Sorted by chemistry → Shredded in sealed environment → Metals separated → Refined → New battery materials",
    },
    "shoes": {
        "title": "How to Recycle or Donate Shoes",
        "steps": [
            "If shoes are still wearable: donate to charity shops, clothing banks, or community sharing groups",
            "If shoes are worn out: place in a textile recycling bank — do not put in general waste",
            "Many shoe brands run take-back programmes — Nike (Reuse-A-Shoe), Timberland, and others accept old shoes in-store",
            "Separate pairs with laces: tie laces together so pairs stay together during processing",
            "Clean shoes lightly before donation — heavily soiled shoes may be rejected by charities",
            "Check local councils: some offer kerbside textile collection that includes footwear",
            "Sports shoes specifically: Nike's Reuse-A-Shoe programme grinds them into sports surfaces",
        ],
        "tip": "Even completely worn-out shoes can be shredded into material for playground surfaces and running tracks.",
        "recycled_into": "Sports surfaces, insulation material, new shoe components, playground flooring",
        "process": "Sorted by condition → Wearable: redistributed → Worn: shredded into rubber/foam → Used in new products",
    },
    "clothes": {
        "title": "How to Recycle or Donate Clothes",
        "steps": [
            "Good condition: donate to charity shops, clothing banks, online platforms (Vinted, Depop, eBay)",
            "Worn out: place in a textile recycling bank — never in general waste, even if badly damaged",
            "Many fashion retailers have in-store take-back schemes: H&M, Zara, M&S, Primark all accept old clothes",
            "Natural fibres (cotton, wool, linen): can be composted if free from synthetic blends and dyes",
            "Sort before donating: charity shops prefer clean, washed items — it reduces their processing cost",
            "Sentimental items: consider repair, repurposing (rags, quilts) or upcycling before recycling",
            "Specialist recyclers (Salvation Army, Humana) accept all textiles regardless of condition",
        ],
        "tip": "Only 1% of clothing is recycled into new clothing — most becomes insulation, rags or filling.",
        "recycled_into": "New fibres, insulation, industrial wiping cloths, stuffing for furniture",
        "process": "Sorted by fibre type and condition → Shredded into fibres → Respun into yarn or pressed into padding",
    },
}